import type { TransactionCategory } from "./types";

export const CATEGORY_LABELS: Record<TransactionCategory, string> = {
  rent: "Rent",
  utilities: "Utilities",
  groceries: "Groceries",
  transit: "Transit",
  subscriptions: "Subscriptions",
  income: "Income",
  transfer: "Transfer",
  coffee: "Coffee",
  coffee_shops: "Coffee Shops",
  food_delivery: "Food Delivery",
  vaping: "Vaping",
  alcohol: "Alcohol",
  personal_vices: "Personal Vices",
  impulse_shopping: "Impulse Shopping",
  shopping: "Shopping",
  dining_out: "Dining Out",
  entertainment: "Entertainment",
  rideshare: "Rideshare",
  transportation: "Transportation",
  phone: "Phone",
  internet: "Internet",
  gym: "Gym",
  insurance: "Insurance",
  health: "Health",
  personal_care: "Personal Care",
  pharmacy: "Pharmacy",
  electronics: "Electronics",
  travel: "Travel",
  fitness: "Fitness",
  home: "Home",
  gifts: "Gifts",
  other: "Other",
};

export const CATEGORY_COLORS: Record<TransactionCategory, string> = {
  rent: "#8B7355",
  utilities: "#6B7280",
  groceries: "#4A7C59",
  transit: "#5B7FA5",
  subscriptions: "#7B68AE",
  income: "#0B8A3E",
  transfer: "#687068",
  coffee: "#6F4E37",
  coffee_shops: "#8B6914",
  food_delivery: "#E85D04",
  vaping: "#DC2626",
  alcohol: "#9D4EDD",
  personal_vices: "#B91C1C",
  impulse_shopping: "#A0522D",
  shopping: "#D97706",
  dining_out: "#C4763C",
  entertainment: "#7C3AED",
  rideshare: "#3D3D3D",
  transportation: "#475569",
  phone: "#4A90D9",
  internet: "#2563EB",
  gym: "#059669",
  insurance: "#6B7280",
  health: "#EF4444",
  personal_care: "#EC4899",
  pharmacy: "#F97316",
  electronics: "#1D4ED8",
  travel: "#0891B2",
  fitness: "#10B981",
  home: "#92400E",
  gifts: "#D946EF",
  other: "#888888",
};

export const CHART_COLORS = {
  spending: "rgb(50, 48, 47)",
  investing: "#0B8A3E",
};
